### ISSUE TITLE
How to change default translation?

### ISSUE THREAD

**Issue by nikolai-shabalin** [hyperform/hyperform-l10n#8]
Hi! Sorry, my bad english.

## Install
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/hyperform/0.9.5/hyperform.min.js"></script>
<script src="hyperform.myLang.js"></script>
<script>
  hyperform(window);
</script>
```

## Html
```
<input type="text" placeholder="number" pattern="^[0-9-()+\s]+$" required="">
```

I enter letters in input and see error - _"Please match the requested format."_

## Need
I need change default value in "PatternMismatch"

	
## for example
`hyperform.myLang.PatternMismatch = 'other text'`

**Comment by Boldewyn** [comment]
Hi.

You can set and/or overwrite translations with `hyperform.addTranslation()`. You set a language with `hyperform.setLanguage()`.

When you load `dist/hyperform.ru.js`, the file does exactly this, adding Russian translations, then setting Hyperform's language to `ru`.

If you want to overwrite specific strings, simply call `addTranslation` again with the ones you want to overwrite:

    hyperform.addTranslation('ru', {
      PatternMismatch: 'some other text'
    });

and only this translation will be updated.

**Comment by nikolai-shabalin** [comment]
Thanks for the quick reply.

```
hyperform.addTranslation('ru', {
  PatternMismatch: 'some other text'
});
```

It works =)
